builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - "-s -w -X main.version={{.Version}} -X main.gitTag={{.Tag}}"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
changelog:
  skip: true
release:
  draft: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
